In [1]:
import torch

In [2]:
print("PyTorch version {}".format(torch.__version__))
print("GPU-enabled installation? {}".format(torch.cuda.is_available()))

PyTorch version 1.8.1+cu102
GPU-enabled installation? True


In [3]:
import numpy as np

In [4]:
t = torch.FloatTensor(2,3)
print(t, t.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.Size([2, 3])


In [5]:
t.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.FloatTensor([[1,2,3], [4,5,6]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
tl = torch.tensor([1,2,3])
t = torch.tensor([1., 2., 3.])
print(f"A 64-bit integer tensor {tl}, {tl.type()}")
print(f"A 32-bit float tensor {t}, {t.type()}")

A 64-bit integer tensor tensor([1, 2, 3]), torch.LongTensor
A 32-bit float tensor tensor([1., 2., 3.]), torch.FloatTensor


In [9]:
t = torch.zeros(2,3)
print(t)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
t_zeros = torch.zeros_like(t)
t_ones = torch.ones(2,3)
t_fives = torch.empty(2,3).fill_(5)
t_random = torch.rand(2,3)
t_normal = torch.randn(2,3)

print(t_zeros)
print(t_ones)
print(t_fives)
print(t_random)
print(t_normal)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[5., 5., 5.],
        [5., 5., 5.]])
tensor([[0.3726, 0.0939, 0.3612],
        [0.0153, 0.2063, 0.2741]])
tensor([[ 0.6114, -0.2654,  1.4462],
        [-1.7033, -0.4660,  0.4819]])


In [14]:
t1 = torch.clone(t)
assert id(t) != id(t1)
t1 = torch.clone(t).detach()
t1

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
a = np.array([1., 2., 3.])
t = torch.tensor(a)

print("NumPy array: {}, type: {}".format(a, a.dtype))
print("Torch tensor: {}, type: {}".format(t, t.dtype))

NumPy array: [1. 2. 3.], type: float64
Torch tensor: tensor([1., 2., 3.], dtype=torch.float64), type: torch.float64


In [16]:
t.numpy()

array([1., 2., 3.])

## Indexing

In [19]:
t = torch.randn(2,3)
t[:,0]

tensor([ 1.1605, -1.4865])

In [20]:
t = torch.randn(5,6)
print(t)
i = torch.tensor([1, 3])
j = torch.tensor([4, 5])
print(t[i])
print(t[i, j])

tensor([[ 0.2769,  0.8294, -0.6906, -0.2495, -1.5907, -0.0366],
        [-0.5929,  1.3712, -1.4938, -1.1266, -0.5346,  0.2572],
        [-2.4509, -0.1837, -1.2592,  0.2079,  0.1854, -0.7483],
        [ 0.5449, -0.3865,  0.8803, -0.0653, -0.0997, -0.6154],
        [ 0.8171, -0.5531,  1.6518, -0.7986, -0.8162, -1.2599]])
tensor([[-0.5929,  1.3712, -1.4938, -1.1266, -0.5346,  0.2572],
        [ 0.5449, -0.3865,  0.8803, -0.0653, -0.0997, -0.6154]])
tensor([-0.5346, -0.6154])


In [21]:
t = t.float()
print(t)
t = t.double()
print(t)
t = t.byte()
print(t)

tensor([[ 0.2769,  0.8294, -0.6906, -0.2495, -1.5907, -0.0366],
        [-0.5929,  1.3712, -1.4938, -1.1266, -0.5346,  0.2572],
        [-2.4509, -0.1837, -1.2592,  0.2079,  0.1854, -0.7483],
        [ 0.5449, -0.3865,  0.8803, -0.0653, -0.0997, -0.6154],
        [ 0.8171, -0.5531,  1.6518, -0.7986, -0.8162, -1.2599]])
tensor([[ 0.2769,  0.8294, -0.6906, -0.2495, -1.5907, -0.0366],
        [-0.5929,  1.3712, -1.4938, -1.1266, -0.5346,  0.2572],
        [-2.4509, -0.1837, -1.2592,  0.2079,  0.1854, -0.7483],
        [ 0.5449, -0.3865,  0.8803, -0.0653, -0.0997, -0.6154],
        [ 0.8171, -0.5531,  1.6518, -0.7986, -0.8162, -1.2599]],
       dtype=torch.float64)
tensor([[  0,   0,   0,   0, 255,   0],
        [  0,   1, 255, 255,   0,   0],
        [254,   0, 255,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0],
        [  0,   0,   1,   0,   0, 255]], dtype=torch.uint8)


## Operations on Tensors

In [22]:
s = torch.tensor(42)
print(s)

tensor(42)


In [23]:
s.item()

42

In [24]:
x = torch.randn(1,3)
print(f"Row vector {x} with size {x.size()}")

Row vector tensor([[ 0.1057, -1.8602,  0.0940]]) with size torch.Size([1, 3])


In [25]:
v = torch.randn(3,1)
print(f"Column vector {v} with size {v.size()}")

Column vector tensor([[-0.1334],
        [-0.9996],
        [ 1.0774]]) with size torch.Size([3, 1])


In [26]:
A = torch.randn(3,3)
print(f"Matrix {A} with size {A.size()}")

Matrix tensor([[-1.6436,  0.2170, -0.9999],
        [-0.9607, -0.7694,  1.3193],
        [-0.4314,  2.0441,  0.8031]]) with size torch.Size([3, 3])


In [27]:
u = torch.matmul(A,v)
print(u)
b = torch.randn(3,1)
y = u + b
print(y)

tensor([[-1.0749],
        [ 2.3187],
        [-1.1205]])
tensor([[-2.7198],
        [ 3.1664],
        [ 1.8595]])


In [28]:
s = torch.matmul(x, torch.matmul(A, v))
print(s.item())

-4.5321736335754395


In [29]:
# common tensor methods (they also have the counterpart in the torch package, e.g. as torch.sum(t))
t = torch.randn(2,3)
t.sum(dim=0)                 
t.t()                   # transpose
t.numel()               # number of elements in tensor
t.nonzero()             # indices of non-zero elements
t.view(-1, 2)           # reorganizes the tensor to these dimensions
t.squeeze()             # removes size 1 dimensions
t.unsqueeze(0)          # inserts a dimension

# operations in the package
torch.arange(0, 10)     # tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.eye(3, 3)         # creates a 3x3 matrix with 1s in the diagonal (identity in this case)
t = torch.arange(0, 3)
torch.cat((t, t))       # tensor([0, 1, 2, 0, 1, 2])
torch.stack((t, t))     # tensor([[0, 1, 2],
                        #         [0, 1, 2]])

tensor([[0, 1, 2],
        [0, 1, 2]])

In [30]:
t_gpu = torch.cuda.FloatTensor(3, 3)   # creation of a GPU tensor
t_gpu.zero_() 

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In [31]:
t_gpu = torch.randn(3, 3, device="cuda:0")
t_gpu

tensor([[ 0.2769, -0.3388,  1.2494],
        [-1.5946,  1.0681,  1.2013],
        [-0.4019, -0.1474, -1.5849]], device='cuda:0')

In [32]:
t = torch.randn(3, 3)   # we could also state explicitly the device to be the CPU with torch.randn(3,3,device="cpu")
t

tensor([[-0.1897, -1.0534, -0.4645],
        [-1.9274, -0.1695,  0.5186],
        [ 0.3544,  1.2793,  0.2769]])